<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_Ampel" Id="{366d4720-12a4-4ad2-980d-adb7cd3a227b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Ampel
VAR_INPUT
	eState : eBetriebszustand;
END_VAR
VAR_OUTPUT
	bAmpelGrun : BOOL;
	bAmpelRot : BOOL;
	bAmpelGelb : BOOL;
END_VAR
VAR
	fbBlinklicht : FB_Blinklicht;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[CASE eState OF
	eBetriebszustand.Off:
	
	
	
	
END_CASE]]></ST>
    </Implementation>
    <LineIds Name="FB_Ampel">
      <LineId Id="17" Count="1" />
      <LineId Id="35" Count="0" />
      <LineId Id="22" Count="0" />
      <LineId Id="21" Count="0" />
      <LineId Id="20" Count="0" />
      <LineId Id="19" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>